### ISSUE TITLE
Global Copilot stopped working today

### ISSUE THREAD

**Issue by Shrekmachine** [Feincraft/Finepilot#1]
Not working this morning. Sometime response is: 
Error: No response from AI service
Sometime simply no result.
Sometimes it works
Some error handling would be good

Cheers Frederic

**Comment by Feincraft** [comment]
The error messages are a result of error handling, however better debugging will be added in 0.7, to be published in 2 days.
If you are using the Open AI service with a free account, you may not get a result because the service is busy.
Unfortunately, Open AI does not always make it clear.
This repo was created for testing purposes, I'll publish a new link to submit issues in the future.
